# Generated by Django 3.2.12 on 2022-10-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chatroom',
            field=models.ManyToManyField(related_name='chatroom', to='chatApp.ChatRoom'),
        ),
    ]
