# Generated by Django 3.2.12 on 2022-10-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_alter_users_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='name',
            new_name='chatname',
        ),
        migrations.AlterField(
            model_name='users',
            name='chatroom',
            field=models.ManyToManyField(to='chatApp.ChatRoom'),
        ),
    ]
