# Generated by Django 3.2.12 on 2022-10-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_auto_20221009_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
