# Generated by Django 3.2.12 on 2022-10-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_rename_creatd_at_messages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatApp.chatroom'),
            preserve_default=False,
        ),
    ]
